In [1]:
import cv2
import numpy as np

vid=cv2.VideoCapture('song.mp4')

mask=np.random.randint(0,255,(100,4))
ret1, frame1 = vid.read()
gray1=cv2.cvtColor(frame1,cv2.COLOR_BGR2GRAY)
points1=cv2.goodFeaturesToTrack(gray1,mask=None,maxCorners=100,qualityLevel=0.5,minDistance=10,blockSize=10)

while vid.isOpened():
    ret, frame = vid.read()
    if not ret:break
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    points2,status,err=cv2.calcOpticalFlowPyrLK(gray1,gray,points1,None,winSize=(15,15),maxLevel=2,criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT,10,0.03))
vid.release()
cv2.destroyAllWindows()


In [4]:

import cv2
import numpy as np
vid=cv2.VideoCapture('song.mp4')
#lk=dict()
ret1, frame1 = vid.read()
gray1=cv2.cvtColor(frame1,cv2.COLOR_BGR2GRAY)
points1=cv2.goodFeaturesToTrack(gray1,mask=None,maxCorners=100,qualityLevel=0.5,minDistance=10,blockSize=10)
print(points1)
mask2=np.zeros_like(frame1)
while vid.isOpened():
    ret, frame = vid.read()
    if not ret:break
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    points2,status,err=cv2.calcOpticalFlowPyrLK(gray1,gray,points1,None,winSize=(15,15),maxLevel=2,criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT,10,0.03))
    newpts=points1[status==1]
    oldpts=points1[status==1]
    for x,(new,old) in enumerate(zip(newpts,oldpts)):
        a,b=new.ravel()#2D->1D Array
        c,d=old.ravel()
        mask2=cv2.line(mask2,(int(a),int(b)),(int(c),int(d)),(0,255,255),4)
        frame=cv2.circle(frame,(int(a),int(b)),5,(0,255,0),-1)
    # print(frame.shape)
    # print(mask2.shape)
    image=cv2.add(frame,mask2)
    cv2.imshow("Frame",image)
    cv2.waitKey(0)
vid.release
cv2.destroyAllWindows()

[[[ 238.  457.]]

 [[ 539.  466.]]

 [[ 543.  454.]]

 [[ 689.  454.]]

 [[ 421.  107.]]

 [[ 240.  470.]]

 [[ 872.  114.]]

 [[ 397.  100.]]

 [[  24.  424.]]

 [[ 415.   98.]]

 [[ 924.  191.]]

 [[1244.   93.]]

 [[ 393.  140.]]

 [[ 882.  134.]]

 [[1259.  491.]]

 [[ 577.  491.]]

 [[ 228.  156.]]

 [[ 237.  129.]]

 [[ 216.  125.]]

 [[  46.  423.]]

 [[ 236.  165.]]

 [[1213.  166.]]

 [[1040.   71.]]

 [[1048.  171.]]]


In [12]:
import cv2
import numpy as np

vid=cv2.VideoCapture('song.mp4')
def find_frame():
    count = 0
    while vid.isOpened():
        ret, frame = vid.read()
        if not ret:
            break
        if count==f:
            return frame
            break
        count += 1
print(f'\nThere are {int(vid.get(cv2.CAP_PROP_FRAME_COUNT))} Frames in Input Video\n')
f =int(input("\nEnter Frame Number :\t"))
fr=find_frame()
gray1=cv2.cvtColor(fr,cv2.COLOR_BGR2GRAY)
points1=cv2.goodFeaturesToTrack(gray1,mask=None,maxCorners=100,qualityLevel=0.5,minDistance=10,blockSize=10)
mask2=np.zeros_like(fr)

while vid.isOpened():
    ret, frame = vid.read()
    if not ret:break
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    points2,status,err=cv2.calcOpticalFlowPyrLK(gray1,gray,points1,None,winSize=(15,15),maxLevel=2,criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT,10,0.03))
    newpts=points1[status==1]
    oldpts=points1[status==1]
    for x,(new,old) in enumerate(zip(newpts,oldpts)):
        a,b=new.ravel()#2D->1D Array
        c,d=old.ravel()
        mask2=cv2.line(mask2,(int(a),int(b)),(int(c),int(d)),(0,255,255),4)
        frame=cv2.circle(frame,(int(a),int(b)),5,(0,255,0),-1)
    image=cv2.add(frame,mask2)
    cv2.imshow("Frame",image)
    cv2.waitKey(0)
vid.release
cv2.destroyAllWindows()


There are 221 Frames in Input Video




Enter Frame Number :	 3


In [1]:
import cv2
import numpy as np
vid=cv2.VideoCapture('song.mp4')
#lk=dict()
frameS=int(input("enter the starting frame: "))
vid.set(cv2.CAP_PROP_POS_FRAMES, frameS)
ret1, frame1 = vid.read()
gray1=cv2.cvtColor(frame1,cv2.COLOR_BGR2GRAY)
points1=cv2.goodFeaturesToTrack(gray1,mask=None,maxCorners=100,qualityLevel=0.5,minDistance=10,blockSize=10)
mask2=np.zeros_like(frame1)
while vid.isOpened():
    ret, frame = vid.read()
    if not ret:break
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    points2,status,err=cv2.calcOpticalFlowPyrLK(gray1,gray,points1,None,winSize=(15,15),maxLevel=2,criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT,10,0.03))
    newpts=points1[status==1]
    oldpts=points1[status==1]
    for x,(new,old) in enumerate(zip(newpts,oldpts)):
        a,b=new.ravel()#2D->1D Array
        c,d=old.ravel()
        mask2=cv2.line(mask2,(int(a),int(b)),(int(c),int(d)),(0,255,255),4)
        frame=cv2.circle(frame,(int(a),int(b)),5,(0,255,0),-1)
    image=cv2.add(frame,mask2)
    cv2.imshow("Frame",image)
    
    cv2.waitKey(0)
vid.release
cv2.destroyAllWindows()

enter the starting frame:  3


In [6]:

import cv2
import numpy as np
vid=cv2.VideoCapture('song.mp4')
frame_count=0
frame_no=int(input("enter frame number:\t"))
while vid.isOpened():
    ret1, frame1 = vid.read()
    if frame_no==frame_count:
        gray1=cv2.cvtColor(frame1,cv2.COLOR_BGR2GRAY)
        points1=cv2.goodFeaturesToTrack(gray1,mask=None,maxCorners=100,qualityLevel=0.5,minDistance=10,blockSize=10)
        mask2=np.zeros_like(frame1)
        break
    frame_count+=1
vid.release()
vid=cv2.VideoCapture('song.mp4')
while vid.isOpened():
    ret, frame = vid.read()
    if not ret:break
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    points2,status,err=cv2.calcOpticalFlowPyrLK(gray1,gray,points1,None,winSize=(15,15),maxLevel=2,criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT,10,0.03))
    newpts=points1[status==1]
    oldpts=points1[status==1]
    for x,(new,old) in enumerate(zip(newpts,oldpts)):
        a,b=new.ravel()#2D->1D Array
        c,d=old.ravel()
        mask2=cv2.line(mask2,(int(a),int(b)),(int(c),int(d)),(0,255,255),4)
        frame=cv2.circle(frame,(int(a),int(b)),5,(0,255,0),-1)
    image=cv2.add(frame,mask2)
    cv2.imshow("Frame",image)
    cv2.waitKey(0)
vid.release()
cv2.destroyAllWindows()

enter frame number:	 3


In [11]:

import cv2
import numpy as np
vid=cv2.VideoCapture('song.mp4')
#lk=dict()
ret1, frame1 = vid.read()
gray1=cv2.cvtColor(frame1,cv2.COLOR_BGR2GRAY)
points1=cv2.goodFeaturesToTrack(gray1,mask=None,maxCorners=100,qualityLevel=0.5,minDistance=10,blockSize=10)
#print(points1)

mask2=np.zeros_like(frame1)
while vid.isOpened():
    ret, frame = vid.read()
    if not ret:break
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    points2,status,err=cv2.calcOpticalFlowPyrLK(gray1,gray,points1,None,winSize=(15,15),maxLevel=2,criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT,10,0.03))
    newpts=points1[status==1]
    oldpts=points1[status==1]
    for x,(new,old) in enumerate(zip(newpts,oldpts)):
        a,b=new.ravel()#2D->1D Array
        c,d=old.ravel()
        mask2=cv2.line(mask2,(int(a),int(b)),(int(c),int(d)),(0,255,255),4)
        frame=cv2.circle(frame,(int(a),int(b)),5,(0,255,0),-1)
    image=cv2.add(frame,mask2)
    cv2.imshow("Frame",image)
    cv2.waitKey(0)
    gray1=gray.copy()
    points1=newpts.reshape(-1,1,2)
vid.release()
cv2.destroyAllWindows()
print("\nDone")



Done


In [12]:
import numpy as np

b=np.arange(12)
a=np.arange(12)
print(a)

print(b)
print(b.reshape(3,4))
print(a.reshape(4,3))

        

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [13]:
import numpy as np

a=np.arange(12)
print(a)
print(a.reshape(3,4,1))
print(a.reshape(-1,1,1))


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]
[[[ 0]]

 [[ 1]]

 [[ 2]]

 [[ 3]]

 [[ 4]]

 [[ 5]]

 [[ 6]]

 [[ 7]]

 [[ 8]]

 [[ 9]]

 [[10]]

 [[11]]]


In [25]:

import cv2
import numpy as np
vid=cv2.VideoCapture('song.mp4')
x,y,h,w=590,170,100,100
roi=(x,y,w,h)
criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT,10,1)
ret1, frame1 = vid.read()
frame_roi=frame1[y:y+h,x:x+w]
hsv=cv2.cvtColor(frame_roi,cv2.COLOR_BGR2HSV)
hist=cv2.calcHist([hsv],[0],None,[180],[0,180])

while vid.isOpened():
    ret, frame = vid.read()
    if not ret:break
    hsv_frame=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    dst=cv2.calcBackProject([hsv_frame],[0],hist,[0,180],1)
    outp,rei=cv2.meanShift(dst,roi,criteria)
    x,y,w,h=roi
    result=cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
    cv2.imshow("Meanshift",result)

    cv2.waitKey(0)
vid.release()
cv2.destroyAllWindows()

In [30]:

import cv2
import numpy as np
vid=cv2.VideoCapture('song.mp4')
x,y,h,w=590,170,100,100
roi=(x,y,w,h)
criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT,10,1)
ret1, frame1 = vid.read()
frame_roi=frame1[y:y+h,x:x+w]
hsv=cv2.cvtColor(frame_roi,cv2.COLOR_BGR2HSV)
hist=cv2.calcHist([hsv],[0],None,[180],[0,180])
while vid.isOpened():
    ret, frame = vid.read()
    if not ret:break
    hsv_frame=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    dst=cv2.calcBackProject([hsv_frame],[0],hist,[0,180],1)
    outp,rei=cv2.meanShift(dst,roi,criteria)
    x,y,w,h=roi
    result=cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
    cv2.imshow("Meanshift",result)
    cv2.waitKey(0)

vid.release()

vid=cv2.VideoCapture('song.mp4')
x,y,h,w=590,170,100,100
roi=(x,y,w,h)
criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT,10,1)
ret1, frame1 = vid.read()
frame_roi=frame1[y:y+h,x:x+w]
hsv=cv2.cvtColor(frame_roi,cv2.COLOR_BGR2HSV)
hist=cv2.calcHist([hsv],[0],None,[180],[0,180])
while vid.isOpened():
    ret, frame = vid.read()
    if not ret:break
    hsv_frame=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    dst=cv2.calcBackProject([hsv_frame],[0],hist,[0,180],1)
    outp,rei=cv2.CamShift(dst,roi,criteria)
    points=cv2.boxPoints(outp).astype(int)
    result=cv2.polylines(frame,[points],True,(255,0,0),2)
    cv2.imshow("Camshift",result)
    cv2.waitKey(0)
vid.release()
cv2.destroyAllWindows()


In [47]:
#BG REMOVAL USING MOG2
import cv2
import numpy as np
vid=cv2.VideoCapture('song.mp4')

bg_subtractor = cv2.createBackgroundSubtractorMOG2(history=500, varThreshold=16, detectShadows=False)
while vid.isOpened():
    ret, frame = vid.read()
    if not ret:break
    fg_mask = bg_subtractor.apply(frame)
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    fg_mask = cv2.morphologyEx(fg_mask, cv2.MORPH_OPEN, kernel)
    cv2.imshow('Original Frame', frame)
    cv2.imshow('Foreground Mask', fg_mask)
    cv2.waitKey(0)
vid.release()
cv2.destroyAllWindows()


In [48]:
#KNN BG REMOVAL
import cv2
import numpy as np
vid=cv2.VideoCapture('song.mp4')

bg_subtractor = cv2.createBackgroundSubtractorKNN(history=500, dist2Threshold=250, detectShadows=False)
while vid.isOpened():
    ret, frame = vid.read()
    if not ret:break
    fg_mask = bg_subtractor.apply(frame)
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    fg_mask = cv2.morphologyEx(fg_mask, cv2.MORPH_OPEN, kernel)
    cv2.imshow('Original Frame', frame)
    cv2.imshow('Foreground Mask', fg_mask)
    cv2.waitKey(0)
vid.release()
cv2.destroyAllWindows()


In [49]:
#
import cv2
import numpy as np
vid=cv2.VideoCapture('song.mp4')

bg_subtractor = cv2.createBackgroundSubtractorKNN(history=400, dist2Threshold=250, detectShadows=False)
count=0
while vid.isOpened():
    ret, frame = vid.read()
    if not ret:break
    count+=1
    fg_mask = bg_subtractor.apply(frame)
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    fg_mask = cv2.morphologyEx(fg_mask, cv2.MORPH_OPEN, kernel)
    cv2.imshow('Original Frame', frame)
    cv2.imshow('Foreground Mask', fg_mask)
    if count > 50:
        break
    cv2.waitKey(0)
vid.release()
cv2.destroyAllWindows()

In [57]:
import cv2
import numpy as np
frame=cv2.imread("Frame_10.jpg")
x,y,h,w=590,170,100,100
roi=(x,y,w,h)
criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT,10,1)
frame_roi=frame[y:y+h,x:x+w]
hsv=cv2.cvtColor(frame_roi,cv2.COLOR_BGR2HSV)
hist=cv2.calcHist([hsv],[0],None,[180],[0,180])
hsv_frame=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
dst=cv2.calcBackProject([hsv_frame],[0],[hist],[0,180],1)
outp,roi=cv2.meanShift(dst,roi,criteria)
x,y,w,h=roi
result=cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
cv2.imshow("Meanshift",result)
cv2.waitKey(0)
cv2.destroyAllWindows()





# import cv2
# import numpy as np
# vid=cv2.VideoCapture('song.mp4')
# x,y,h,w=590,170,100,100
# roi=(x,y,w,h)
# criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT,10,1)
# ret1, frame1 = vid.read()
# frame_roi=frame1[y:y+h,x:x+w]
# hsv=cv2.cvtColor(frame_roi,cv2.COLOR_BGR2HSV)
# hist=cv2.calcHist([hsv],[0],None,[180],[0,180])

# while vid.isOpened():
#     ret, frame = vid.read()
#     if not ret:break
#     hsv_frame=cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
#     dst=cv2.calcBackProject([hsv_frame],[0],hist,[0,180],1)
#     outp,rei=cv2.meanShift(dst,roi,criteria)
#     x,y,w,h=roi
#     result=cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
#     cv2.imshow("Meanshift",result)
#     cv2.waitKey(0)
# vid.release()
# cv2.destroyAllWindows()

error: OpenCV(4.8.1) :-1: error: (-5:Bad argument) in function 'calcBackProject'
> Overload resolution failed:
>  - hist is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'hist'


In [2]:
import cv2
import numpy as np

frame = cv2.imread("Frame_10.jpg")
x, y, h, w = 590, 170, 100, 100
roi = (x, y, w, h)
criteria = (cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 10, 1)
frame_roi = frame[y:y + h, x:x + w]
hsv_roi = cv2.cvtColor(frame_roi, cv2.COLOR_BGR2HSV)
# mask = cv2.inRange(hsv_roi, (0, 30, 10), (180, 255, 255))
hist = cv2.calcHist([hsv_roi], [0], None, [180], [0, 180])
# cv2.normalize(hist, hist, 0, 255, cv2.NORM_MINMAX)
hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
dst = cv2.calcBackProject([hsv_frame], [0], hist, [0, 180], 1)
outp, roi = cv2.meanShift(dst, roi, criteria)
x, y, w, h = roi
result = cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 255), 2)
cv2.imshow("Meanshift", result)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [3]:
"""
#GRABCUT MODEL
import cv2
import numpy as np

image = cv2.imread('cbn_grup2.jpg')
mask = np.zeros(image.shape[:2], np.uint8)
rect = (50, 50, 450, 290)
bgd_model = np.zeros((1, 65), np.float64)
fgd_model = np.zeros((1, 65), np.float64)
cv2.grabCut(image, mask, rect, bgd_model, fgd_model, 5, cv2.GC_INIT_WITH_RECT)
mask2 = np.where((mask == 2) | (mask == 0), 0, 1).astype('uint8')
result = image * mask2[:, :, np.newaxis]
cv2.imshow('Original Image', image)
cv2.imshow('Foreground Extraction', result)
cv2.waitKey(0)
cv2.destroyAllWindows()




#haarcascade face detection
import cv2
face = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
image_path = 'cbn_grup2.jpg'
img = cv2.imread(image_path)
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
faces = face.detectMultiScale(gray_img, scaleFactor=1.3, minNeighbors=5)
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)
cv2.imshow('Detected Faces', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
"""


import cv2
import numpy as np
import os

vid=cv2.VideoCapture('mySkillVideo.avi')
face = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
count=0
while vid.isOpened():
    ret, frame = vid.read()
    if not ret:break

    #haarcascade
    gray_img = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face.detectMultiScale(gray_img, scaleFactor=1.3, minNeighbors=5)
    if len(faces)>0:
        count+=1
        #grabcut
        mask = np.zeros(frame.shape[:2], np.uint8)
        rect = (50, 50, 450, 290)
        bgd_model = np.zeros((1, 65), np.float64)
        fgd_model = np.zeros((1, 65), np.float64) 
        cv2.grabCut(frame, mask, rect, bgd_model, fgd_model, 5, cv2.GC_INIT_WITH_RECT)
        mask2 = np.where((mask == 2) | (mask == 0), 0, 1).astype('uint8')
        result = frame * mask2[:, :, np.newaxis]

        for (x, y, w, h) in faces:
            cv2.rectangle(result, (x, y), (x+w, y+h), (255, 0, 0), 2)
        cv2.imwrite(f'anyimage{count}',result)
        cv2.waitKey(0)

    # cv2.imshow('result',result)
                   
vid.release()
cv2.destroyAllWindows()







haarcascade_eye_tree_eyeglasses.xml
haarcascade_eye.xml
haarcascade_frontalcatface_extended.xml
haarcascade_frontalcatface.xml
haarcascade_frontalface_alt2.xml
haarcascade_frontalface_alt_tree.xml
haarcascade_frontalface_alt.xml
haarcascade_frontalface_default.xml
haarcascade_fullbody.xml
haarcascade_lefteye_2splits.xml
haarcascade_license_plate_rus_16stages.xml
haarcascade_lowerbody.xml
haarcascade_profileface.xml
haarcascade_righteye_2splits.xml
haarcascade_russian_plate_number.xml
haarcascade_smile.xml
haarcascade_upperbody.xml